#
# 실제 마인크래프트 서버가 아닌, 후원 연동을 위한 서버
#
Server:
  ip: "127.0.0.1"
  port: 8888

#
# 이벤트 화이트리스트 기능
#
SendEvent:
  donation: true
  chat: true

Url:
  # 생방송 링크
  youtube: ""
  # 알림창 Url
  toonation: ""
  # 알림창 Url
  weflab: ""